# SwiftLint 0.32

disabled_rules:
  - cyclomatic_complexity
  - force_cast
  - force_try
  - function_parameter_count
  - line_length
  - nesting
  - trailing_whitespace
  - unused_optional_binding
  - void_return
  - xctfail_message
  - identifier_name

opt_in_rules:
  - anyobject_protocol
  - array_init
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_first_not_nil
  - convenience_type
  - empty_count
  - empty_string
  - explicit_init
  - file_header
  - first_where
  - identical_operands
  - last_where
  - legacy_random
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - modifier_order
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
  - no_extension_access_modifier
  - operator_usage_whitespace
  - private_action
  - private_outlet
  - prohibited_super_call
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - redundant_nil_coalescing
  - single_test_class
  - sorted_first_last
  - static_operator
  - strict_fileprivate
  - toggle_bool
  - unneeded_parentheses_in_closure_argument
  - unused_import
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - yoda_condition

excluded:
  - Pods

file_header:
  required_pattern: |
                    \/\/
                    \/\/  .*\.swift
                    \/\/  .*?
                    \/\/
                    \/\/  Created by .*? on \d{2}\/\d{2}\/\d{4}\.
                    \/\/  Copyright © \d{4}\ .*?. All rights reserved\.
                    \/\/

file_length:
  warning: 350

identifier_name:
  min_length:
    warning: 0
  max_length:
    warning: 50

type_name:
  max_length:
    warning: 50
